[package]
edition = "2021"
name = "worklog_calendar"
version = "0.1.0"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
